spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&serviceTimezone=UTC
    username: root
    password: 430122
mybatis:
  mapper-locations: mapper/*Mapper.xml