spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 430122ly
mybatis:
  mapper-locations: mapper/*Mapper.xml